version: "3.4"

networks:
  backend:

services:

  db_pg:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    #Порт проброшен внутри сети контейнеров, доступа с хоста нету.
    ports:
      - "5432"
    networks:
      - backend
    env_file:
      - ~/test/DockerHW/hw2/.env

  python_django:
    image: python:3.8
    depends_on:
      - db_pg
    restart: unless-stopped
    volumes:
      - /root/test/DockerHW/hw2/stocks_products:/stocks_products
      - static_volume:/root/test/DockerHW/hw2/stocks_products/static/
    #По команде "docker-compose up -d --build" создадутся контейнеры по докерФайлам после чего
    # можно будет запустить docker-compose
    build:
      context: ~/test/DockerHW/hw2/
      dockerfile: Dockerfile
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    networks:
      - backend
    env_file:
      - ~/test/DockerHW/hw2/.env

  web:
    image: nginx
    build: ./nginx
    volumes:
      - /root/test/DockerHW/hw2/stocks_products/static:/home/app/python_django/static
      - static_volume:/root/test/DockerHW/hw2/stocks_products/static/
    ports:
      - "1337:80"
    networks:
      - backend
    depends_on:
      - python_django

volumes:
    pg_data:
    static_volume:
